image: docker:20.10.8

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - apk add --no-cache docker-compose
    - echo "Building Frontend/Backend Docker Image"
  script:
    - docker build -t frontend -f ./frontend/Dockerfile ./frontend/ 
    - docker build -t backend -f ./backend/Dockerfile ./backend/ 
  after_script:  
    - echo "Successful! Frontend/Backend are builded!" 

backend-test-job:
  stage: test
  before_script:
    - cd backend
    - apk add --no-cache docker-compose
    - echo "Running unit tests."
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:    
    - echo "Backend tests Done!"

frontend-test-job:
  stage: test
  before_script:
    - cd frontend
    - apk add --no-cache docker-compose
    - echo "Running unit tests."
  script:
    - docker-compose run --entrypoint "npm run test" frontend
  after_script:        
    - echo "Frontend Tests Done!" 

deploy-job:
  stage: deploy  
  before_script:
    - docker build -t fmaachadoo/workshopcientrega02:frontend -f ./frontend/Dockerfile ./frontend/ 
    - echo "$PASSWORD" | docker login -u "$USER" "docker.io" --password-stdin
    - echo "Deploying! 🤞"
  script:    
    - docker build -t fmaachadoo/workshopcientrega02:backend -f ./backend/Dockerfile ./backend/ 
    - docker push fmaachadoo/workshopcientrega02:frontend
    - docker push fmaachadoo/workshopcientrega02:backend
  after_script:
    - echo "✅ The application has been successfully deployed! ✅"